### ISSUE TITLE
Odoo16 update + Gevent / Websocket support

### ISSUE THREAD

**Issue by schwahue** [wbsouza/odoo-traefik#2]
Hi wbsouza,

I am attempting to configure Odoo16 with traefik. However, I am encountering some roadblocks. What are the headers configuration needed to get traefik to work with Odoo16?

Regards

**Comment by wbsouza** [comment]
Hey, I just saw your message today, I will try to get it running on Odoo 16 this week and see how it goes.

**Comment by schwahue** [comment]
Hi wbsouza, Thank you for replying. The issue particularly lies with the websocket, I keep getting error 400

**Comment by schwahue** [comment]
Hi I've found this on one of Odoo issue, might be helpful. I will try it and post here.

# # global config
- "traefik.enable=true"
- "traefik.docker.network=traefik-swarm"
# # main routers 8069 web rule "/*"
- "traefik.http.routers.${NAME_SERVICE_TRAEFIK}.tls=true"
- "traefik.http.routers.odoo16.entrypoints=https"
- "traefik.http.routers.odoo16.rule=Host(traefik.odoo16.com)"
- "traefik.http.routers.odoo16.service=odoo16@docker"
- "traefik.http.routers.odoo16.middlewares=gzip"
- "traefik.http.services.odoo16.loadbalancer.server.port=8069"
# # main routers 8072 websocket rule "/websocket"
- "traefik.http.routers.backend-websock.tls=true"
- "traefik.http.routers.backend-websock.entrypoints=https"
- "traefik.http.routers.backend-websock.rule=Path(/websocket) && Host(traefik.odoo16.com)"
- "traefik.http.routers.backend-websock.middlewares=upgradeheader,sslheader,gzip"
- "traefik.http.routers.backend-websock.service=backend-websock@docker"
- "traefik.http.services.backend-websock.loadbalancer.server.port=8072"
# # upgrade headers
- "traefik.http.middlewares.upgradeheader.headers.customRequestHeaders.Upgrade=websocket"
- "traefik.http.middlewares.upgradeheader.headers.customRequestHeaders.Connection=upgrade"
- "traefik.http.middlewares.upgradeheader.headers.hostsproxyheaders=websocket,Upgrade"
- "traefik.http.middlewares.upgradeheader.headers.forcestsheader=true"
- "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
# # gzip compress
- "traefik.http.middlewares.gzip.compress=true"

**Comment by schwahue** [comment]
https://github.com/odoo/odoo/issues/106339#issuecomment-1617584516

**Comment by schwahue** [comment]
This works for me now

**Comment by wbsouza** [comment]
Great! Thanks for your efforts, I will need this solution to run a Odoo 16 now :-)
